### ISSUE TITLE
teleinfo for haos

### ISSUE THREAD

**Issue by nicoxygen** [fmartinou/hassio-addons#1]
Salut donc dans haos l'adresse mqtt est core-mosquitto:18...
les entités remontent bien ainsi que l'appareil mais tu ne retrouve pas les entités dans l'appareil pour créer une carte rapidement, je ne sais plus si c'est un fonctionnement normal de ton module

ci-joint le debug:
09:09:36.722  INFO teleinfo-mqtt:
    Starting teleinfo-mqtt with configuration = {
      emitInterval: 10,
      hassDiscovery: true,
      hassDiscoveryPrefix: 'homeassistant',
      logLevel: 'DEBUG',
      mqttBaseTopic: 'teleinfo',
      mqttUrl: 'mqtt://core-mosquitto:1883',
      mqttUser: 'mqtt',
      mqttPassword: '<hidden>',
      serial: '/dev/ttyUSB0'
    }
09:09:36.748  INFO teleinfo-mqtt: Connecting to MQTT broker [mqtt://core-mosquitto:1883]
09:09:37.032  INFO teleinfo-mqtt: Connected to MQTT broker [mqtt://core-mosquitto:1883]
09:09:37.033  INFO teleinfo-mqtt: Connecting to port [/dev/ttyUSB0]
09:09:37.057  INFO teleinfo-mqtt: Connected to port [/dev/ttyUSB0]
09:09:39.896 DEBUG teleinfo-mqtt: Ignoring MQTT emission because of emit interval (Emit interval : 10 - Last emit time : 1638259776402 - Current time : 1638259779896
09:09:41.318 DEBUG teleinfo-mqtt: Ignoring MQTT emission because of emit interval (Emit interval : 10 - Last emit time : 1638259776402 - Current time : 1638259781318
09:09:42.724 DEBUG teleinfo-mqtt: Ignoring MQTT emission because of emit interval (Emit interval : 10 - Last emit time : 1638259776402 - Current time : 1638259782724
09:09:44.149 DEBUG teleinfo-mqtt: Ignoring MQTT emission because of emit interval (Emit interval : 10 - Last emit time : 1638259776402 - Current time : 1638259784149
09:09:45.573 DEBUG teleinfo-mqtt: Ignoring MQTT emission because of emit interval (Emit interval : 10 - Last emit time : 1638259776402 - Current time : 1638259785573
09:09:46.997 DEBUG teleinfo-mqtt: Dispatch frame {"ADCO":{"raw":"700501411465","value":700501411465},"OPTARIF":{"raw":"HC..","value":"HC"},"ISOUSC":{"raw":"60","value":60},"HCHC":{"raw":"153401133","value":153401133},"HCHP":{"raw":"269576704","value":269576704},"PTEC":{"raw":"HP..","value":"HP"},"IINST":{"raw":"045","value":45},"IMAX":{"raw":"061","value":61},"PAPP":{"raw":"10190","value":10190},"HHPHC":{"raw":"A","value":"A"}}
09:09:47.001  INFO teleinfo-mqtt: Publish configuration for tag ADCO for discovery to topic [homeassistant/sensor/teleinfo/700501411465_adco/config]
09:09:47.008  INFO teleinfo-mqtt: Publish configuration for tag OPTARIF for discovery to topic [homeassistant/sensor/teleinfo/700501411465_optarif/config]
09:09:47.008  INFO teleinfo-mqtt: Publish configuration for tag ISOUSC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_isousc/config]
09:09:47.009  INFO teleinfo-mqtt: Publish configuration for tag HCHC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hchc/config]
09:09:47.011  INFO teleinfo-mqtt: Publish configuration for tag HCHP for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hchp/config]
09:09:47.012  INFO teleinfo-mqtt: Publish configuration for tag PTEC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_ptec/config]
09:09:47.013  INFO teleinfo-mqtt: Publish configuration for tag IINST for discovery to topic [homeassistant/sensor/teleinfo/700501411465_iinst/config]
09:09:47.014  INFO teleinfo-mqtt: Publish configuration for tag IMAX for discovery to topic [homeassistant/sensor/teleinfo/700501411465_imax/config]
09:09:47.015  INFO teleinfo-mqtt: Publish configuration for tag PAPP for discovery to topic [homeassistant/sensor/teleinfo/700501411465_papp/config]
09:09:47.016  INFO teleinfo-mqtt: Publish configuration for tag HHPHC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hhphc/config]
09:09:47.018 DEBUG teleinfo-mqtt: Publish frame to topic [teleinfo/700501411465]
09:09:47.019 DEBUG teleinfo-mqtt: 
    ADCO: {
      "raw": "700501411465",
      "value": 700501411465
    }
    --
    OPTARIF: {
      "raw": "HC..",
      "value": "HC"
    }
    --
    ISOUSC: {
      "raw": "60",
      "value": 60
    }
    --
    HCHC: {
      "raw": "153401133",
      "value": 153401133
    }
    --
    HCHP: {
      "raw": "269576704",
      "value": 269576704
    }
    --
    PTEC: {
      "raw": "HP..",
      "value": "HP"
    }
    --
    IINST: {
      "raw": "045",
      "value": 45
    }
    --
    IMAX: {
      "raw": "061",
      "value": 61
    }
    --
    PAPP: {
      "raw": "10190",
      "value": 10190
    }
    --
    HHPHC: {
      "raw": "A",
      "value": "A"
    }

**Comment by fmartinou** [comment]
Salut @nicoxygen ,

Merci beaucoup pour le troubleshoot 👍  .

Je vais changer la valeur par défaut du host du broker mqtt.
(ce qui est bizarre, c'est que j'ai un autre addon pour Deltadore et la personne qui l'a testé m'a dit que la valeur par défaut était `homeassistant`) 🤔 

> les entités remontent bien ainsi que l'appareil mais tu ne retrouves pas les entités dans l'appareil pour créer une carte rapidement,

Je ne comprends pas bien ce point.
Je pousse sur MQTT les configs pour toutes les entités
```
09:09:47.001 INFO teleinfo-mqtt: Publish configuration for tag ADCO for discovery to topic [homeassistant/sensor/teleinfo/700501411465_adco/config]
09:09:47.008 INFO teleinfo-mqtt: Publish configuration for tag OPTARIF for discovery to topic [homeassistant/sensor/teleinfo/700501411465_optarif/config]
09:09:47.008 INFO teleinfo-mqtt: Publish configuration for tag ISOUSC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_isousc/config]
09:09:47.009 INFO teleinfo-mqtt: Publish configuration for tag HCHC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hchc/config]
09:09:47.011 INFO teleinfo-mqtt: Publish configuration for tag HCHP for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hchp/config]
09:09:47.012 INFO teleinfo-mqtt: Publish configuration for tag PTEC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_ptec/config]
09:09:47.013 INFO teleinfo-mqtt: Publish configuration for tag IINST for discovery to topic [homeassistant/sensor/teleinfo/700501411465_iinst/config]
09:09:47.014 INFO teleinfo-mqtt: Publish configuration for tag IMAX for discovery to topic [homeassistant/sensor/teleinfo/700501411465_imax/config]
09:09:47.015 INFO teleinfo-mqtt: Publish configuration for tag PAPP for discovery to topic [homeassistant/sensor/teleinfo/700501411465_papp/config]
09:09:47.016 INFO teleinfo-mqtt: Publish configuration for tag HHPHC for discovery to topic [homeassistant/sensor/teleinfo/700501411465_hhphc/config]
```

Donc normalement, tout remonte dans HA (integration, device, entities) et le device ressemble à qq chose comme ça
![image](https://user-images.githubusercontent.com/16061231/144013054-009c37e6-51c5-430a-93c1-cf1dbbb27e1a.png)

**Comment by nicoxygen** [comment]
pour l'adreese mqtt: que ce soit core-mosquitto ou homeassistant ne change rien
par contre le lien de dépot est: https://github.com/fmartinou/hassio-addons
je sais pas si tu l'as changé car le lien contenait .git

- j'ai bien un appareil linky avec toutes les entités
- - j'ai aussi un appareil téléinfo !! bizarre à moins que..

![teleinfo](https://user-images.githubusercontent.com/17491075/144282465-fdea27b1-55b3-4c51-b05d-1c52457c6851.png)

**Comment by fmartinou** [comment]
L'url à saisir dans home-assistant est normalement le lien pour faire un git clone via https ?
Donc https://github.com/fmartinou/hassio-addons.git

Si j'indique https://github.com/fmartinou/hassio-addons, haos n'arrivera pas à cloner le dépôt puisque c'est une URL dont la réponse http contient de l'html.
Non ?

**Comment by fmartinou** [comment]
> pour l'adresse mqtt: que ce soit core-mosquitto ou homeassistant ne change rien

Je n'ai pas compris.
Je pensais que `homeassistant` ne resolvait pas alors que `core-mosquitto` si...

Du coup, il en est quoi?
Les 2 résolvent la même chose ?
Les 2 fonctionnent ?

**Comment by nicoxygen** [comment]
les deux fonctionnent j'ai testé

**Comment by nicoxygen** [comment]
non je viens de me rendre compte seul core-mosquitto fonctionne, homeassistant ne retourne pas d'erreurs par contre les infos sont figés donc ce n'est pas bon, j'enverrai la capture d'ecran des infos en temps réel

**Comment by fmartinou** [comment]
> non je viens de me rendre compte seul core-mosquitto fonctionne

Ok merci pour le feedback
