### ISSUE TITLE
La variable Mqtt server (server Mqtt sur une autre machine) n'est pas pris en compte avec la nouvelle version 3.5.0

### ISSUE THREAD

**Issue by Sabjul33** [fmartinou/hassio-addons#19]
J'ai un serveur Mqtt déporté et après avoir passé la mise à jour impossible de faire fonctionner mes volets.
Je viens de me rendre compte que la configuration ne prend pas en compte l'ip renseigné dans la configuration de l'application.
"mqtt_host" : "localhost".

Je suis repassé en version 3.4.3 et tout refonctionne et je vois dans la configuration l'adresse ip renseignée.

PS : où peut-on trouver dans Ha le fichier de conf options.json ?

Merci par avance.

**Comment by dmorvant56** [comment]
Bonjour, je contaste le même pb.
En mettant une configuration bidon : 

![image](https://github.com/fmartinou/hassio-addons/assets/113779559/42b13ce2-673d-4c4b-9b8c-b9005a869095)

On voit bien dans la log que la partie tydom est bien valorisée mais pas la mqtt et qu'elle reste avec les valeurs par défaut : 
![image](https://github.com/fmartinou/hassio-addons/assets/113779559/9f50eaa2-4e8e-429d-8a01-f7e2a11d7693)

**Comment by Sabjul33** [comment]
Info : je suis en version 2024.06.0 de HA

**Comment by sebastioune** [comment]
Bonjour 
Meme comportement avec un serveur MQTT local (HA 2024.6.1)

**Comment by Sabjul33** [comment]
Bonjour,
Merci pour la réactivité !!!!!
Update en 3.5.1 problème résolu 👍👍👍
Ok également en 2024.6.1.
