### ISSUE TITLE
Impossible d'activer le module

### ISSUE THREAD

**Issue by CaporalDead** [fmartinou/hassio-addons#4]
Bonjour,

Tout d'abord merci pour votre travail. Je n'arrive pas à activer l'extension via Home Assistant. J'utilise un RPi4+ avec l'OS HA. J'ai saisi la configuration minimum et elle semble s'enregistrer correctement :

![Capture d’écran_2021-12-26_21-58-11](https://user-images.githubusercontent.com/1705597/147419966-bb4712f2-c51b-42a8-beb6-7ab9b6fe67c8.png)

Mais au moment de démarrer le module je continue d'avoir cette erreur : 

![Capture d’écran_2021-12-26_21-57-35](https://user-images.githubusercontent.com/1705597/147419990-67305b34-92e1-47c2-ba25-4868a688c979.png)

Ce qui est bizarre c'est que si j'utilise l'image Docker avec la même configuration minimum sur mon PC en local je n'ai aucun soucis, le service se lance sans problème. Je n'arrive pas à avoir plus de logs car je n'ai rien dans les journaux de HA ou de l'extension.

Si vous avez une idée je suis tout à fait preneur ! Merci

**Comment by CaporalDead** [comment]
Bon, il faut bien un premier boulet :sweat_smile: , j'ai forcé le type de chaque variable dans le yml pour être sûr que tout corresponde aux types du fichier `config.yml` et ça a fini par fonctionner 

```yaml
TYDOM_MAC: "001A25*****"
TYDOM_IP: "****"
TYDOM_PASSWORD: "*****"
TYDOM_ALARM_PIN: "9999"
TYDOM_ALARM_HOME_ZONE: 1
TYDOM_ALARM_NIGHT_ZONE: 2
MQTT_HOST: "****"
MQTT_USER: "****"
MQTT_PASSWORD: "****"
MQTT_PORT: 1883
MQTT_SSL: false
log_level: "debug"
```

**Comment by fmartinou** [comment]
Hello,

Ravi de voir que tu t'en es sorti 😉

**Comment by CaporalDead** [comment]
Ça reste tout de même assez bizarre tout de même de devoir faire ça, j'imagine que je ne serais pas le seul à avoir ce soucis. Je ne sais pas si vous avez réussi à le reproduire de votre côté. Je serais ravi de faire une PR pour la doc si le soucis est bien avéré

**Comment by fmartinou** [comment]
Rien de bizarre ; la version initiale du descripteur du pin de l'alarme était défini en integer, d'où le problème. Cela a déjà été corrigé en string il y a 2 semaines environ. J'imagine qu'il faut faire un refresh des repositories depuis la UI de home-assistant pour que ça soit mis à jour ?

https://github.com/fmartinou/hassio-addons/commit/cff8ab7ef5cd3de0bdd5f68e91447dc25d7d9988

**Comment by CaporalDead** [comment]
Le problème est apparu après une fresh install de Home Assistant (et donc du module tydom2mqtt) la semaine dernière donc après la correction semble-t-il et j'avais bien le soucis de ne pouvoir valider le formulaire. Après le problème ne se pose plus aujourd'hui et au pire des cas cette issue permettra de donner une solution.

**Comment by fadu57** [comment]
Bonjour
Beau travail ce module. Mais ...
Si seulement j'arrivais à le faire fonctionner
Et ça fait des jours que je cherche 
Toujours le même constat : on me réclame en permanence le TYDOM_PASSWORD
Et lorsque j'en saisis un, il disparaît ensuite dans le log
![TMFpg89jal](https://github.com/user-attachments/assets/4be793a5-bd57-4aae-a908-7fc428674379)
![ZcIPfUWWIO](https://github.com/user-attachments/assets/3c560fc8-790f-4390-b417-daae0e757485)
Je précise que je suis sur un box domotique Home Assistant Green (NABU CASA) toute neuve
Aurai-je oublié quelque-chose ?

**Comment by fmartinou** [comment]
Hello,

Le fait de fournir les vars `DELTADORE_LOGIN` et `DELTADORE_PASSWORD` provoque le fait que le module va utiliser ces credentials pour retrouver le `TYDOM_PASSWORD` en utilisant le Cloud Deltadore.

Si tu connais ce `TYDOM_PASSWORD` (le cas idéal), alors il ne faut pas renseigner les vars `DELTADORE_LOGIN` et `DELTADORE_PASSWORD`
++

**Comment by fadu57** [comment]
Super réponse rapide ... mais, après t'avoir lu
J'ai désinstallé / réinstaller
Je ne connais pas le TYDOM_PASSWORD (j'avais testé des pwd avec ce que j'avais lu sur des forums ....)
Donc, en réinstallant, j'ai configuré avec les vars DELTADORE_LOGIN et DELTADORE_PASSWORD et en laissant "TYDOM_PASSWORD" dans la ligne TYDOM_PASSWORD (en laissant vide, j'ai un "échec de l'enregistrement ..."
![firefox_QEDSECWxvr](https://github.com/user-attachments/assets/86704d5f-b413-4ff4-8dff-4b6d049e74de)
Mais rien n'y fait !
![3efLqQR8k8](https://github.com/user-attachments/assets/d61ab8c0-c084-4605-810f-39026decc839)

**Comment by fmartinou** [comment]
Ca ressemble au fait que la récupération du password depuis l'api Cloud de deltadore échoue 😞 

C'est ici que c'est fait :
- https://github.com/tydom2mqtt/tydom2mqtt/blob/master/app/configuration/Configuration.py#L151-L154
- https://github.com/tydom2mqtt/tydom2mqtt/blob/master/app/tydom/TydomClient.py#L80-L129

Essaie de relancer avec les logs en debug ; ça apportera peut-être plus de détails

**Comment by fadu57** [comment]
Si c'est l'api Cloud de Delta Dore, on n'est pas rendu en effet 🥴
Étrange quand même car ça fait déjà 3 jours que je cherche ...
J'ai relancé en debug mais pas plus d'infos
![4-18jGqCE0ia](https://github.com/user-attachments/assets/7960d760-f0f1-44fa-b4fe-ca0954a4c883)

Et MQTT Explorer qui remonte quand même des messages ...
![3yBb2ntXio](https://github.com/user-attachments/assets/28e75c60-ee8b-4b83-8d81-730aac4a8170)

**Comment by fmartinou** [comment]
Les messages mqtt ne sont pas liés à cet addon mais à l'activité d'autres composants, non ?

Pour le problème de password, il faudrait le retour d'autres utilisateurs qui utilisent leurs credentials deltadore pour voir si ça marche mieux ou pas chez eux 🤷‍♂️

**Comment by fmartinou** [comment]
https://github.com/tydom2mqtt/tydom2mqtt/issues/209

**Comment by fadu57** [comment]
Alors AVIS AUX AUTRES UTILISATEURS

**Comment by fmartinou** [comment]
Tu peux ouvrir une issue sur https://github.com/tydom2mqtt/tydom2mqtt/issues
(ça rendra ta demande plus visible)

Désolé de pas pouvoir plus t'aider en l'état 🤷‍♂️

**Comment by fadu57** [comment]
Merci quand même ... et si jamais il te venait une autre idée ...

**Comment by fmartinou** [comment]
Tu n'as pas moyen de récupérer le mot de passe à la tydom ?

A une époque, il était possible de reset son mot de passe tydom ; https://tydom2mqtt.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password

Je ne sais pas si ce workaround fonctionne encore aujourd'hui...

**Comment by fadu57** [comment]
2021, le workaround. J'essaierai. Je suis en train de télécharger la V3, mais c'est laborieux quand même avec ces systèmes 'trop fermés' !
