### ISSUE TITLE
unable to save configuration

### ISSUE THREAD

**Issue by krisshomeassistant** [fmartinou/hassio-addons#6]
Hi,

if you can help i would be very grateful

I have added the repository to my HASS and when trying to configure my tydom the UI will not allow me to save my configuration.

I have checked several times now just incase i was missing something put no it will not save any ideas why?

I had the tydom2mqtt set up with no problems for weeks until the new update a week ago and have never managed to get it to work since?

Thanks again.

Kris

**Comment by fmartinou** [comment]
Hi,

HASS lets you save the configuration only when at least 1 input have been changed; is that your case?

You can also take a look at the [validation schema defined for `tydom2mqtt` here](https://github.com/fmartinou/hassio-addons/blob/main/tydom2mqtt/config.yml#L36-L47).

You'll find there the expected data types (`str`, `int`...) for the configuration variables.
By default, variables are required unless you see a `?` at the end (ex: `TYDOM_IP: str?`).

With that information, I hope you'll managed to identify which field is in error.

**Comment by krisshomeassistant** [comment]
Thank you for the quick reply.

So iv just had a quick look and I changed the Alarm password from 9999 to 123456 and Hass is now accepting the save request.

Very strange. thank you again for all your hard work getting this up and running.

Take care and have a great day

Best Regards

Kris
