### ISSUE TITLE
Fonctionnement avec Tydom 2.0

### ISSUE THREAD

**Issue by FROCHE38** [fmartinou/hassio-addons#8]
Bonjour. 
Est-ce que l'add-on HA est compatible avec Tydom 2.0 ?
Si oui, quel est le mot de passe à utiliser. Est-ce celui du compte de l'app DeltaDore dans laquelle on met son email ?

**Comment by fmartinou** [comment]
Bonjour,

Pour la tydom 2.0, je ne suis pas sûr.
Certains utilisateurs ont remonté une incompatibilité mais je ne sais pas si ça concerne tous les utilisateurs de cette box ou non.
Voir les détails ici (vers la fin de la discussion).
https://github.com/fmartinou/tydom2mqtt/issues/12


Concernant le mot de passe, par contre, je suis sûr ; ce n'est pas le mot de passe du compte Delta dore mais bien un autre mot de passe associé à la tydom.
Depuis les dernières versions de l'application mobile Delta Dore, malheureusement, il n'est plus possible de définir/réinitialiser ce mot de passe.
Le trick, c'est de télécharger une ancienne version de l'application 🙁 [comme décrit dans la documentation](https://fmartinou.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password).

**Comment by fmartinou** [comment]
Si tu as déjà la tydom 2.0, tu peux tester ; ça ne coûte rien 😉

Et si tu n'es pas encore équipé, oriente toi plutôt vers 1.0 qui sera moins chère et plus intégrable (à HA, Jeedom...).
(on en trouve même parfois sur Leboncoin pour ~50€)

**Comment by FROCHE38** [comment]
Hello, j'ai une tydom 2.0 car vendue avec l'alarme DeltaDore. J'ai choisi
cette marque car mes volets volants utilisent le protocole X3D. J'ai déjà
téléchargé la version 3.06 et je vais tenter le reset password. On verra...

Le dim. 20 févr. 2022 à 19:22, fmartinou ***@***.***> a
écrit :

**Comment by dominig** [comment]
**TyDom 2 Intégration solution.**
Je viens d'intégrer ma TyDom 2.0 (en pratique une TyDom Pro, le modèle qui se monte sur un rail DIN et qui gère X3D et Zigbee. J'ai réussi à faire fonctionner mes volets X3D mais je ne vois pas les device Zigbee.

Il faut faire 4 choses.
  - (Facile) Ajouter en Yalm un PIN pour l'alarme qui n’apparaît pas dans la WEB UI avec 6 digits. Autrement le parser plante.
  - (Facile) créer un 'user:motDePasse' dans Home Assistant pour que la connection vers MQTT broker fonctionne.
  - (Facile) utiliser "homeassistant" comme IP pour la conection vers MQTT, localhost ne marche.
 - (Compliqué) Récupérer le passe de la TyDom2. Je l'ai fait avec Charles Proxy qui permet de hacker une connection ssl. Les solution via l'ancienne TyDom App V.3 ou l'App de K-line, ne marchent pas. Le mot de passe est dynamique et peut changer (stabilité à voir avec le temps). 
 J'ai décrit toute la procédure pour la publier dans le forum de de Home Assistant, mais mon post a été refusé car je suis un nouvel utilisateur et que j'ai des liens et des images. Je n'ai pas de réponse pour une solution pour contourner cette limitation. Dommage car la procédure est tout sauf simple et je la partagerai avec plaisir.
   Il devrait d'ailleurs être possible de la simplifier dans le but de l'intégrer à tydom2mqtt mais pour l'instant mon problème immédiat serait plutôt de voir les devices ZigBee et de pouvoir faire du pairing sans passer par le TyDom App V.4.

**Comment by dominig** [comment]
@fmartinou C'est avec plaisir que je publierai la procédure détaillée mais comme nouvel inscrit sur le wiki de tydom2mqtt, les limitations en lien et capture d'écrans sont incompatible avec la complexité de la procédure.
Si tu peux me donner un truc pour que ce soit fait, soit par moi soit par un tier, je suis preneur.
